todolist with vue single-file(js->vue)
havenothingtosay/todoList pull request #2
Opened 2017-02-02 05:37 UTC by havenothingtosay

js那层需要也改成.vue吗？就是怎么样组织他的结构比较好？

2017-02-02 12:13 UTC, csvwolf requested changes
💯

2017-02-02 12:13 UTC, csvwolf commented on index.html
> +  <div id="todolist">
这里只要留一个渲染 vue 的入口就行了 剩下的可以在 App.vue 中做

2017-02-02 12:13 UTC, csvwolf commented on hasDone.vue
> +    props: ['prop'],
？？？叫 prop 地球人谁看的懂！

2017-02-02 12:13 UTC, csvwolf commented on hasDone.vue
> +    <li v-for='hasdone in prop' v-if='hasdone.iscomplete'>
<del>这个 v-if 有啥用</del> 哦 todo 共用列表啊 也行吧

2017-02-02 12:13 UTC, csvwolf commented on index.js
> +var todolist = new Vue({
用 es6 有 const 这种可以用了

2017-02-02 12:13 UTC, csvwolf commented on needDo.vue
> +      <span contenteditable=true>{{ todo.content }}</span>
"true"

2017-02-02 12:13 UTC, csvwolf commented on needDo.vue
> +        x.content = target.previousSibling.previousSibling.previousSibling.previousSibling.innerHTML;
所以说为什么要这么辛苦传 dom 拉 你把绑定的值传进去不行吗！

2017-02-02 12:13 UTC, csvwolf commented on webpack.config.js
> +            'scss': 'vue-style-loader!css-loader!sass-loader',
你到底用 scss 还是 sass 呀

2017-02-02 12:28 UTC, havenothingtosay commented on index.html
> +  <div id="todolist">
是要多加一级父级的.vue的意思吗？把<h1>和<input>这些放到父级.vue里，然后父级里在渲染hasDone.vue和needDo.vue？

2017-02-02 12:29 UTC, csvwolf commented on index.html
> +  <div id="todolist">
@havenothingtosay yes

2017-02-02 12:32 UTC, havenothingtosay commented on webpack.config.js
> +            'scss': 'vue-style-loader!css-loader!sass-loader',
这个。。。我不知道是什么。。。。我按照webpack-simple执行，它自己生成的。。。。。。。。其实我一个都没用好像

2017-02-02 12:32 UTC, havenothingtosay commented on index.html
> +  <div id="todolist">
好的

2017-02-02 12:35 UTC, havenothingtosay commented on needDo.vue
> +        x.content = target.previousSibling.previousSibling.previousSibling.previousSibling.innerHTML;
我是要把改完的值赋给绑定的todo.content，直接获取的话它还是原来的值

2017-02-02 12:52 UTC, csvwolf commented on needDo.vue
> +        x.content = target.previousSibling.previousSibling.previousSibling.previousSibling.innerHTML;
@havenothingtosay 加一个change 监听

2017-02-03 06:18 UTC, csvwolf approved these changes
well, 基本 ok 。Congratulations!

2017-02-03 06:18 UTC, csvwolf commented on needDo.vue
> +      edittwo(x,target) {
editTwo??

2017-02-03 11:42 UTC, merged